# Site settings
title:       "The % Project"
header_title: "The Percentage Project"
webmaster:      "Alexander Goodkind <alexander@goodkind.io>"
author: "The University of Pennsylvania Women in Computer Science (Penn WiCS) "
description: "The #PercentageProject is an artistic, visual outlet for data collected from an anonymous survey of Computer Science students. The Percentage Project was founded in 2018 at the University of Pennsyvlania with the goal of showcasing data along with advocates to put a face to the statistic. We aim to encourage reflection and conversation on the experiences of minority students beyond just how many minority students we have."

baseurl:    "" # no trailing slash !
url:         "https://percentageproject.com"
date_format: "%-d.%m.%Y"

collections:
  years:
    output: true
    permalink: /year/:path

defaults:
  - scope:
      path: "photos/photos_compressed"
    values:
      image: "latest"

  - scope:
      path: "photos/2018_photos_compressed"
    values:
      image: "2018"

# include trailing slash !!!
favicon_path: "/assets/img/favicons/"  
css_path: "/assets/css/"
js_path: "/assets/js/"

# Google Analytics
google_analytics_tracking_code: UA-137802583-1

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
